apiVersion: v1
kind: PersistentVolume
metadata:
  name: talep-takip-media-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany  # Birden fazla pod'un erişimi için
  hostPath:
    path: "/mnt/talep-takip-media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talep-takip-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
