apiVersion: v1
kind: PersistentVolume
metadata:
  name: talep-takip-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/talep-takip-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talep-takip-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
